// Recorridos nacionales — Máxima Autoridad · SCE Ecuador
// Fuente: cuenta oficial @Competencia_Ec en X — Período nov 2024 – abr 2026
window.VISITS = [

  // ── QUITO — sede institucional ───────────────────────────────────────────
  {
    code: "UIO01", name: "Quito", capital: "Quito", province: "Pichincha",
    lat: -0.2295, lon: -78.5243,
    date: "2024-11-15", dateLong: "15 NOV 2024",
    type: "cooperación", expediente: "SCE-UIO-2024-001",
    flag: { type: "ecuador" }, isOrigin: true,
    event: "Reunión bilateral · República Dominicana",
    eventLong: "Cooperación Bilateral · <em>República Dominicana</em>",
    organizer: "SCE · Dirección de Cooperación Internacional",
    brief: "El Superintendente se reunió con <em>Ito Bisonó</em>, Ministro de Industria, Comercio y Mipymes de la República Dominicana, para abordar temas de cooperación bilateral en materia de competencia económica.",
    stats: { dias: 1, distancia: 0 }
  },
  {
    code: "UIO02", name: "Quito", capital: "Quito", province: "Pichincha",
    lat: -0.2295, lon: -78.5243,
    date: "2025-01-14", dateLong: "14 ENE 2025",
    type: "cooperación", expediente: "SCE-UIO-2025-001",
    flag: { type: "ecuador" }, isOrigin: true,
    event: "Reunión · Embajador de Panamá en Ecuador",
    eventLong: "Cooperación Institucional · <em>Embajada de Panamá</em>",
    organizer: "SCE · Dirección de Cooperación Internacional",
    brief: "El Superintendente se reunió con el Embajador de Panamá en Ecuador, <em>Alfredo Montaner</em>, en su sede diplomática para tratar temas de cooperación institucional en materia de competencia.",
    stats: { dias: 1, distancia: 0 }
  },
  {
    code: "UIO03", name: "Quito", capital: "Quito", province: "Pichincha",
    lat: -0.2295, lon: -78.5243,
    date: "2025-02-19", dateLong: "19 FEB 2025",
    type: "cooperación", expediente: "SCE-UIO-2025-002",
    flag: { type: "ecuador" }, isOrigin: true,
    event: "Reunión · Regulación IA y Mercados Digitales",
    eventLong: "Cooperación Internacional · <em>Regulación IA y Mercados Digitales</em>",
    organizer: "SCE · Dirección de Cooperación Internacional",
    brief: "El Superintendente se reunió con un exparlamentario europeo para abordar la importancia de la <em>regulación de la inteligencia artificial</em> y los mercados digitales en el marco de la competencia económica.",
    stats: { dias: 1, distancia: 0 }
  },
  {
    code: "UIO04", name: "Quito", capital: "Quito", province: "Pichincha",
    lat: -0.2295, lon: -78.5243,
    date: "2025-05-28", dateLong: "28 MAY 2025",
    type: "cooperación", expediente: "SCE-UIO-2025-003",
    flag: { type: "ecuador" }, isOrigin: true,
    event: "Reunión · Cámara Ecuador-Británica",
    eventLong: "Cooperación Internacional · <em>Cámara Ecuador-Británica (GBE)</em>",
    organizer: "SCE · Dirección de Cooperación Internacional",
    brief: "El Superintendente se reunió con <em>Diego Gordón</em>, Director Ejecutivo de la Cámara Ecuador-Británica, para dar seguimiento a propuestas de cooperación y asistencia técnica impulsadas por universidades del Reino Unido.",
    stats: { dias: 1, distancia: 0 }
  },
  {
    code: "UIO05", name: "Quito", capital: "Quito", province: "Pichincha",
    lat: -0.2295, lon: -78.5243,
    date: "2025-07-02", dateLong: "02 JUL 2025",
    type: "rendición", expediente: "SCE-UIO-2025-004",
    flag: { type: "ecuador" }, isOrigin: true,
    event: "Rendición de Cuentas SCE 2025",
    eventLong: "Rendición de Cuentas <em>SCE 2025</em>",
    organizer: "SCE · Dirección de Comunicación",
    brief: "La SCE realizó su <em>Rendición de Cuentas 2025</em>. El Superintendente pronunció el discurso de apertura: \"No ilusionamos con palabras, transformamos con hechos. Garantizamos vigilancia, técnica, transparencia y acción\". Evento transmitido en vivo por Facebook.",
    stats: { dias: 1, distancia: 0 }
  },
  {
    code: "UIO06", name: "Quito", capital: "Quito", province: "Pichincha",
    lat: -0.2295, lon: -78.5243,
    date: "2026-04-08", dateLong: "08 ABR 2026",
    type: "rendición", expediente: "SCE-UIO-2026-001",
    flag: { type: "ecuador" }, isOrigin: true,
    event: "Rendición de Cuentas SCE · Transmisión en vivo",
    eventLong: "Rendición de Cuentas <em>SCE — Transmisión en vivo</em>",
    organizer: "SCE · Dirección de Comunicación",
    brief: "Transmisión en LIVE de la <em>Rendición de Cuentas 2025</em> de la Superintendencia de Competencia Económica, con intervención del Superintendente dirigida a la ciudadanía.",
    stats: { dias: 1, distancia: 0 }
  },
  {
    code: "UIO07", name: "Quito", capital: "Quito", province: "Pichincha",
    lat: -0.2295, lon: -78.5243,
    date: "2026-04-14", dateLong: "14 ABR 2026",
    type: "cooperación", expediente: "SCE-UIO-2026-002",
    flag: { type: "ecuador" }, isOrigin: true,
    event: "Reunión · American Bar Association (ABA)",
    eventLong: "Cooperación Internacional · <em>American Bar Association (ABA)</em>",
    organizer: "SCE · Dirección de Cooperación Internacional",
    brief: "El Superintendente sostuvo una reunión con representantes de la <em>American Bar Association (ABA)</em> para abordar temas de cooperación internacional en el ámbito jurídico de la competencia económica.",
    stats: { dias: 1, distancia: 0 }
  },
  {
    code: "UIO08", name: "Quito", capital: "Quito", province: "Pichincha",
    lat: -0.2295, lon: -78.5243,
    date: "2026-04-15", dateLong: "15 ABR 2026",
    type: "rendición", expediente: "SCE-UIO-2026-003",
    flag: { type: "ecuador" }, isOrigin: true,
    event: "Rendición de Cuentas · CPCCS",
    eventLong: "Rendición de Cuentas <em>CPCCS</em> · Vicepresidente FTCS",
    organizer: "FTCS · SCE",
    brief: "El Superintendente, en calidad de <em>Vicepresidente de la Función de Transparencia y Control Social (FTCS)</em>, asistió a la Rendición de Cuentas del CPCCS, fortaleciendo la transparencia y articulación entre instituciones.",
    stats: { dias: 1, distancia: 0 }
  },
  {
    code: "UIO09", name: "Quito", capital: "Quito", province: "Pichincha",
    lat: -0.2295, lon: -78.5243,
    date: "2026-04-16", dateLong: "16 ABR 2026",
    type: "rendición", expediente: "SCE-UIO-2026-004",
    flag: { type: "ecuador" }, isOrigin: true,
    event: "Rendición de Cuentas · SRI",
    eventLong: "Rendición de Cuentas <em>Servicio de Rentas Internas (SRI)</em>",
    organizer: "FTCS · SCE",
    brief: "El Superintendente participó en la Rendición de Cuentas del <em>Servicio de Rentas Internas (SRI)</em>, reafirmando el compromiso con la transparencia institucional y la articulación del Estado.",
    stats: { dias: 1, distancia: 0 }
  },
  {
    code: "UIO10", name: "Quito", capital: "Quito", province: "Pichincha",
    lat: -0.2295, lon: -78.5243,
    date: "2026-04-21", dateLong: "21 ABR 2026",
    type: "rendición", expediente: "SCE-UIO-2026-005",
    flag: { type: "ecuador" }, isOrigin: true,
    event: "Rendición de Cuentas · Superint. Protección de Datos",
    eventLong: "Rendición de Cuentas · <em>Superint. de Protección de Datos Personales</em>",
    organizer: "FTCS · SCE",
    brief: "El Superintendente estuvo presente en la rendición de cuentas de la <em>Superintendencia de Protección de Datos Personales</em>, destacando la importancia del Estado en proteger los datos personales de los ecuatorianos.",
    stats: { dias: 1, distancia: 0 }
  },
  {
    code: "UIO11", name: "Quito", capital: "Quito", province: "Pichincha",
    lat: -0.2295, lon: -78.5243,
    date: "2026-04-22", dateLong: "22 ABR 2026",
    type: "rendición", expediente: "SCE-UIO-2026-006",
    flag: { type: "ecuador" }, isOrigin: true,
    event: "Rendición de Cuentas · Instituto Superior Universitario Japón",
    eventLong: "Rendición de Cuentas · <em>Instituto Superior Universitario Japón</em>",
    organizer: "SCE · Dirección de Comunicación",
    brief: "El Superintendente asistió a la rendición de cuentas del <em>Instituto Superior Universitario Japón</em>, continuando la creación de lazos con la academia para promover la cultura de competencia económica.",
    stats: { dias: 1, distancia: 0 }
  },
  {
    code: "UIO12", name: "Quito", capital: "Quito", province: "Pichincha",
    lat: -0.2295, lon: -78.5243,
    date: "2026-04-24", dateLong: "24 ABR 2026",
    type: "rendición", expediente: "SCE-UIO-2026-007",
    flag: { type: "ecuador" }, isOrigin: true,
    event: "Rendición de Cuentas · Secretaría Técnica FTCS",
    eventLong: "Rendición de Cuentas · <em>Secretaría Técnica FTCS</em>",
    organizer: "FTCS · SCE",
    brief: "El Superintendente, en calidad de Vicepresidente de la <em>FTCS</em>, participó en la rendición de cuentas de la Secretaría Técnica del Comité de Coordinación de la Función, trabajando conjuntamente para fortalecer la integridad pública.",
    stats: { dias: 1, distancia: 0 }
  },
  {
    code: "UIO13", name: "Quito", capital: "Quito", province: "Pichincha",
    lat: -0.2295, lon: -78.5243,
    date: "2026-04-28", dateLong: "28 ABR 2026",
    type: "rendición", expediente: "SCE-UIO-2026-008",
    flag: { type: "ecuador" }, isOrigin: true,
    event: "Rendición de Cuentas · Defensoría del Pueblo",
    eventLong: "Rendición de Cuentas · <em>Defensoría del Pueblo</em>",
    organizer: "FTCS · SCE",
    brief: "El Superintendente, en calidad de Vicepresidente de la <em>Función de Transparencia y Control Social (FTCS)</em>, participó en la rendición de cuentas de la Defensoría del Pueblo, continuando el trabajo en beneficio de todo el Ecuador.",
    stats: { dias: 1, distancia: 0 }
  },

  // ── RECORRIDOS NACIONALES — fuera de Quito ───────────────────────────────
  {
    code: "CUE", name: "Cuenca", capital: "Cuenca", province: "Azuay",
    lat: -2.9001, lon: -79.0059,
    date: "2024-11-13", dateLong: "13 NOV 2024",
    type: "reunión", expediente: "SCE-NAC-2024-001",
    flag: { type: "ecuador" },
    event: "Reunión · Cámara de Turismo del Azuay",
    eventLong: "Reunión Institucional · <em>Cámara de Turismo del Azuay</em>",
    organizer: "SCE · Intendencia Regional Austro",
    brief: "El Superintendente se reunió con Juan Vanegas (presidente Cámara de Turismo del Azuay) y José Luis Correa (director) para acordar trabajo conjunto en fortalecimiento de la <em>industria turística</em> y la competencia económica del sector.",
    stats: { dias: 1, distancia: 477 }
  },
  {
    code: "SNA", name: "Santa Elena", capital: "Santa Elena", province: "Santa Elena",
    lat: -2.2268, lon: -80.8589,
    date: "2025-01-30", dateLong: "30 ENE 2025",
    type: "convenio", expediente: "SCE-NAC-2025-001",
    flag: { type: "ecuador" },
    event: "Convenio UPSE y Alcaldía · Santa Elena",
    eventLong: "Firma de Convenio · <em>UPSE y Alcaldía de Santa Elena</em>",
    organizer: "SCE · Dirección Técnica de Abogacía",
    brief: "El Superintendente firmó un convenio con la <em>UPSE</em> (Universidad Estatal Península de Santa Elena) para impulsar la enseñanza de la competencia económica en la provincia, y celebró un acuerdo con la Alcaldía de Santa Elena reafirmando el compromiso institucional con la ciudadanía.",
    stats: { dias: 1, distancia: 360 }
  },
  {
    code: "SDO", name: "Santo Domingo", capital: "Santo Domingo", province: "Santo Domingo de los Tsáchilas",
    lat: -0.2517, lon: -79.1700,
    date: "2025-07-03", dateLong: "03 JUL 2025",
    type: "convenio", expediente: "SCE-NAC-2025-002",
    flag: { type: "ecuador" },
    event: "Convenio Marco · Sesión Solemne 48 años de cantonización",
    eventLong: "Convenio Marco · <em>Sesión Solemne 48 años de cantonización</em>",
    organizer: "SCE · Dirección Técnica de Abogacía",
    brief: "Durante la sesión solemne por los <em>48 años de cantonización</em> de Santo Domingo, el Superintendente firmó un Convenio Marco con el Alcalde, fortaleciendo la vinculación institucional con los gobiernos locales de la región.",
    stats: { dias: 1, distancia: 120 }
  },
  {
    code: "GYE", name: "Guayaquil", capital: "Guayaquil", province: "Guayas",
    lat: -2.1710, lon: -79.9224,
    date: "2025-07-23", dateLong: "23 JUL 2025",
    type: "sesión", expediente: "SCE-NAC-2025-003",
    flag: { type: "ecuador" },
    event: "Sesión FTCS · 489 años de fundación de Guayaquil",
    eventLong: "Sesión Ordinaria <em>FTCS</em> · 489 años de fundación de Guayaquil",
    organizer: "SCE · Función de Transparencia y Control Social",
    brief: "El Superintendente participó en la Sesión Ordinaria de la <em>Función de Transparencia y Control Social (FTCS)</em>, en el marco de la sesión solemne por los 489 años de fundación de Guayaquil, reafirmando el compromiso con una competencia económica justa y solidaria.",
    stats: { dias: 1, distancia: 420 }
  },
  {
    code: "GPS1", name: "Galápagos", capital: "Santa Cruz", province: "Galápagos",
    lat: -0.7383, lon: -90.3625,
    date: "2025-10-02", dateLong: "02 OCT 2025",
    type: "foro", expediente: "SCE-NAC-2025-004",
    flag: { type: "ecuador" }, isGalapagos: true,
    event: "1er Foro Global · Inauguración · Competencia, Mercados Digitales y Sostenibilidad",
    eventLong: "<em>1er Foro Global</em> · Inauguración · Competencia, Mercados Digitales y Sostenibilidad",
    organizer: "SCE · Isla Santa Cruz, Galápagos",
    brief: "Inauguración del <em>1er Foro Global de Competencia, Mercados Digitales y Sostenibilidad</em> en la isla Santa Cruz. La apertura estuvo marcada por la entrega de las llaves de la ciudad por la alcaldesa <em>Fanny Uribe</em>. Se desarrollaron conferencias de la Unión Europea, CAF y Microsoft sobre inteligencia artificial, mercados digitales y retos de la competencia. Participaron delegaciones de República Dominicana, Eslovenia, Rumanía y la Comisión Europea.",
    stats: { dias: 1, distancia: 1000 }
  },
  {
    code: "GPS2", name: "Galápagos", capital: "Santa Cruz", province: "Galápagos",
    lat: -0.7383, lon: -90.3625,
    date: "2025-10-03", dateLong: "03 OCT 2025",
    type: "foro", expediente: "SCE-NAC-2025-005",
    flag: { type: "ecuador" }, isGalapagos: true,
    event: "1er Foro Global · Jornada Ciudadana · GAD Santa Cruz",
    eventLong: "<em>1er Foro Global</em> · Jornada Ciudadana · GAD Santa Cruz, Galápagos",
    organizer: "SCE · GAD Santa Cruz, Galápagos",
    brief: "Segunda jornada del <em>1er Foro Global de Competencia, Mercados Digitales y Sostenibilidad</em>. En el GAD de Santa Cruz se cumplió un evento paralelo para toda la ciudadanía, en el que el Superintendente ratificó el compromiso de la SCE con las Islas Galápagos.",
    stats: { dias: 1, distancia: 0 }
  },
  {
    code: "LOJ1", name: "Loja", capital: "Loja", province: "Loja",
    lat: -3.9931, lon: -79.2042,
    date: "2026-01-15", dateLong: "15 ENE 2026",
    type: "congreso", expediente: "SCE-NAC-2026-001",
    flag: { type: "ecuador" },
    event: "I Congreso Internacional · Inauguración · UTPL Loja",
    eventLong: "<em>I Congreso Internacional</em> · Inauguración · Emprendimiento y Competencia Económica",
    organizer: "UTPL · SCE",
    brief: "Inauguración del <em>I Congreso Internacional de Emprendimiento y Competencia Económica</em> en la UTPL, Loja. La apertura fue presidida por el Intendente General Técnico en representación del Superintendente, quien destacó la importancia de la competencia económica.",
    stats: { dias: 1, distancia: 670 }
  },
  {
    code: "LOJ2", name: "Loja", capital: "Loja", province: "Loja",
    lat: -3.9931, lon: -79.2042,
    date: "2026-01-16", dateLong: "16 ENE 2026",
    type: "congreso", expediente: "SCE-NAC-2026-002",
    flag: { type: "ecuador" },
    event: "I Congreso Internacional · Segunda Jornada · UTPL Loja",
    eventLong: "<em>I Congreso Internacional</em> · Segunda Jornada · UTPL Loja",
    organizer: "UTPL · SCE",
    brief: "Con la presencia del Superintendente arrancó la segunda jornada del <em>I Congreso Internacional de Emprendimiento y Competencia Económica</em> en la UTPL, Loja.",
    stats: { dias: 1, distancia: 0 }
  },
  {
    code: "SD2", name: "Santo Domingo", capital: "Santo Domingo", province: "Santo Domingo de los Tsáchilas",
    lat: -0.2517, lon: -79.1700,
    date: "2026-02-11", dateLong: "11 FEB 2026",
    type: "jornada", expediente: "SCE-NAC-2026-003",
    flag: { type: "ecuador" },
    event: "Jornada de Competencia · UNIANDES",
    eventLong: "Jornada de Competencia <em>UNIANDES</em> · Reuniones con actores productivos",
    organizer: "UNIANDES · SCE",
    brief: "El Superintendente cumplió una agenda de trabajo en Santo Domingo: dictó una <em>Jornada de Competencia en UNIANDES</em> y sostuvo reuniones con actores productivos del sector, fortaleciendo la cultura de competencia económica en la región.",
    stats: { dias: 1, distancia: 120 }
  }
];
